/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const AMessage: typeof import('@arco-design/web-vue')['Message']
  const AModal: typeof import('@arco-design/web-vue')['Modal']
}
