import { OrgTree } from "../../lib/components/org-lane-chart/data";
import { deepClone } from "../../lib/tools/index";

export enum ProjectType {
  // 项目类型
  PROJECT_BASE = "PROJECT_BASE",
  // 单项工程
  SINGLE_PROJECT = "SINGLE_PROJECT",
  // 单位工程
  UNIT_PROJECT = "UNIT_PROJECT",
  // 分部工程
  DIVISION_PROJECT = "DIVISION_PROJECT",
  // 分项清单
  ITEM_CHECKLIST = "ITEM_CHECKLIST",
  // 工序
  ITEM_PROCESS = "ITEM_PROCESS",
}

export const orgDatas: OrgTree<number | string>[] = [
  {
    id: 1,
    projectId: 100,
    parentId: 0,
    projectLevelId: 1,
    projectNumber: "a00001",
    subProjectName: "环球爆破重建项目",
    materialEquipment: null,
    materialEquipmentConsistent: null,
    machineUse: null,
    machineUseConsistent: null,
    laborPerson: null,
    laborPersonConsistent: null,
    levelItemType: ProjectType.PROJECT_BASE,
    children: [
      {
        id: "1714894226275405826",
        projectId: 100,
        parentId: 1,
        projectLevelId: "1714894226275405826",
        projectNumber: "12222abcdefg",
        subProjectName: "导入单项测试234567",
        materialEquipment: null,
        materialEquipmentConsistent: null,
        machineUse: null,
        machineUseConsistent: null,
        laborPerson: null,
        laborPersonConsistent: null,
        levelItemType: ProjectType.SINGLE_PROJECT,
        children: [
          {
            id: "1714894226275405827",
            projectId: 100,
            parentId: "1714894226275405826",
            projectLevelId: "1714894226275405827",
            projectNumber: "3223123b3344bcdefg",
            subProjectName: "单位工程",
            materialEquipment: 0,
            materialEquipmentConsistent: 1,
            machineUse: 0,
            machineUseConsistent: 1,
            laborPerson: 0,
            laborPersonConsistent: 1,
            levelItemType: ProjectType.UNIT_PROJECT,
            children: [
              {
                id: "1714902296099549185",
                projectId: 100,
                parentId: 0,
                projectLevelId: "1714894226275405827",
                projectNumber: "03223232323",
                subProjectName: "分buzhou",
                materialEquipment: 0,
                materialEquipmentConsistent: null,
                machineUse: 0,
                machineUseConsistent: null,
                laborPerson: 0,
                laborPersonConsistent: null,
                levelItemType: ProjectType.DIVISION_PROJECT,
                children: [
                  {
                    id: "1714902296099549185",
                    projectId: 100,
                    parentId: 0,
                    projectLevelId: "1714894226275405827",
                    projectNumber: "03223232323",
                    subProjectName: "分项",
                    materialEquipment: 0,
                    materialEquipmentConsistent: null,
                    machineUse: 0,
                    machineUseConsistent: null,
                    laborPerson: 0,
                    laborPersonConsistent: null,
                    levelItemType: ProjectType.ITEM_CHECKLIST,
                    children: [],
                    isProfessionSubcontract: null,
                    sumConsistent: null,
                    materialInfo: null,
                    materialEquipmentNumber: null,
                    materialEquipmentUnit: null,
                  },
                ],
                isProfessionSubcontract: null,
                sumConsistent: null,
                materialInfo: null,
                materialEquipmentNumber: null,
                materialEquipmentUnit: null,
              },

              {
                id: "1714902296099549185",
                projectId: 100,
                parentId: 0,
                projectLevelId: "1714894226275405827",
                projectNumber: "03223232323",
                subProjectName: "分项",
                materialEquipment: 0,
                materialEquipmentConsistent: null,
                machineUse: 0,
                machineUseConsistent: null,
                laborPerson: 0,
                laborPersonConsistent: null,
                levelItemType: ProjectType.ITEM_CHECKLIST,
                children: [],
                isProfessionSubcontract: null,
                sumConsistent: null,
                materialInfo: null,
                materialEquipmentNumber: null,
                materialEquipmentUnit: null,
              },
              {
                id: "1714902296099549185",
                projectId: 100,
                parentId: 0,
                projectLevelId: "1714894226275405827",
                projectNumber: "03223232323",
                subProjectName: "分项",
                materialEquipment: 0,
                materialEquipmentConsistent: null,
                machineUse: 0,
                machineUseConsistent: null,
                laborPerson: 0,
                laborPersonConsistent: null,
                levelItemType: ProjectType.ITEM_CHECKLIST,
                children: [],
                isProfessionSubcontract: null,
                sumConsistent: null,
                materialInfo: null,
                materialEquipmentNumber: null,
                materialEquipmentUnit: null,
              },

              // {
              //   id: "1714894226275405827",
              //   projectId: 100,
              //   parentId: "1714894226275405826",
              //   projectLevelId: "1714894226275405827",
              //   projectNumber: "0000000",
              //   subProjectName: "特殊的分部",
              //   isEmpty: true,
              //   materialEquipment: 0,
              //   materialEquipmentConsistent: 1,
              //   machineUse: 0,
              //   machineUseConsistent: 1,
              //   laborPerson: 0,
              //   laborPersonConsistent: 1,
              //   levelItemType: ProjectType.DIVISION_PROJECT,
              //   isProfessionSubcontract: 0,
              //   sumConsistent: null,
              //   materialInfo: null,
              //   materialEquipmentNumber: null,
              //   materialEquipmentUnit: null,
              //   children: [
              //     {
              //       id: "1714902296099549185",
              //       projectId: 100,
              //       parentId: 0,
              //       projectLevelId: "1714894226275405827",
              //       projectNumber: "03223232323",
              //       subProjectName: "分项",
              //       materialEquipment: 0,
              //       materialEquipmentConsistent: null,
              //       machineUse: 0,
              //       machineUseConsistent: null,
              //       laborPerson: 0,
              //       laborPersonConsistent: null,
              //       levelItemType: ProjectType.ITEM_CHECKLIST,
              //       children: [],
              //       isProfessionSubcontract: null,
              //       sumConsistent: null,
              //       materialInfo: null,
              //       materialEquipmentNumber: null,
              //       materialEquipmentUnit: null,
              //     },
              //     {
              //       id: "1714902296099549185",
              //       projectId: 100,
              //       parentId: 0,
              //       projectLevelId: "1714894226275405827",
              //       projectNumber: "03223232323",
              //       subProjectName: "分项",
              //       materialEquipment: 0,
              //       materialEquipmentConsistent: null,
              //       machineUse: 0,
              //       machineUseConsistent: null,
              //       laborPerson: 0,
              //       laborPersonConsistent: null,
              //       levelItemType: ProjectType.ITEM_CHECKLIST,
              //       children: [],
              //       isProfessionSubcontract: null,
              //       sumConsistent: null,
              //       materialInfo: null,
              //       materialEquipmentNumber: null,
              //       materialEquipmentUnit: null,
              //     },
              //   ],
              // },
            ],
            isProfessionSubcontract: 0,
            sumConsistent: null,
            materialInfo: null,
            materialEquipmentNumber: null,
            materialEquipmentUnit: null,
          },
        ],
        isProfessionSubcontract: null,
        sumConsistent: null,
        materialInfo: null,
        materialEquipmentNumber: null,
        materialEquipmentUnit: null,
      },
      {
        id: "1714829600137293826",
        projectId: 100,
        parentId: 1,
        projectLevelId: "1714829600137293826",
        projectNumber: "12222abcdef",
        subProjectName: "导入单项测试234567",
        materialEquipment: null,
        materialEquipmentConsistent: null,
        machineUse: null,
        machineUseConsistent: null,
        laborPerson: null,
        laborPersonConsistent: null,
        levelItemType: ProjectType.SINGLE_PROJECT,
        children: [
          {
            id: "1714850304812347393",
            projectId: 100,
            parentId: "1714829600137293826",
            projectLevelId: "1714850304812347393",
            projectNumber: "123dedd",
            subProjectName: "测试单位",
            materialEquipment: 0,
            materialEquipmentConsistent: 0,
            machineUse: 0,
            machineUseConsistent: 1,
            laborPerson: 0,
            laborPersonConsistent: 1,
            levelItemType: ProjectType.UNIT_PROJECT,
            children: [
              {
                id: "1714850750498324481",
                projectId: 100,
                parentId: "1714850304812347393",
                projectLevelId: "1714850750498324481",
                projectNumber: "df222",
                subProjectName: "测试分部2",
                materialEquipment: 1,
                materialEquipmentConsistent: null,
                machineUse: 0,
                machineUseConsistent: null,
                laborPerson: 0,
                laborPersonConsistent: null,
                levelItemType: ProjectType.DIVISION_PROJECT,
                children: [
                  {
                    id: "1714882248802734081",
                    projectId: 100,
                    parentId: 0,
                    projectLevelId: "1714850750498324481",
                    projectNumber: "010201005027",
                    subProjectName: "振冲密实(不填料)",
                    materialEquipment: 0,
                    materialEquipmentConsistent: null,
                    machineUse: 0,
                    machineUseConsistent: null,
                    laborPerson: 0,
                    laborPersonConsistent: null,
                    levelItemType: ProjectType.ITEM_CHECKLIST,
                    children: [],
                    isProfessionSubcontract: null,
                    sumConsistent: null,
                    materialInfo: null,
                    materialEquipmentNumber: null,
                    materialEquipmentUnit: null,
                  },
                ],
                isProfessionSubcontract: 0,
                sumConsistent: null,
                materialInfo: null,
                materialEquipmentNumber: null,
                materialEquipmentUnit: null,
              },
            ],
            isProfessionSubcontract: 0,
            sumConsistent: null,
            materialInfo: null,
            materialEquipmentNumber: null,
            materialEquipmentUnit: null,
          },
          {
            id: "1714829600137293827",
            projectId: 100,
            parentId: "1714829600137293826",
            projectLevelId: "1714829600137293827",
            projectNumber: "3223123b3344bcdef",
            subProjectName: "导入单位测试23456",
            materialEquipment: 0,
            materialEquipmentConsistent: 1,
            machineUse: 0,
            machineUseConsistent: 1,
            laborPerson: 1,
            laborPersonConsistent: 0,
            levelItemType: ProjectType.UNIT_PROJECT,
            children: [],
            isProfessionSubcontract: 0,
            sumConsistent: null,
            materialInfo: null,
            materialEquipmentNumber: null,
            materialEquipmentUnit: null,
          },
        ],
        isProfessionSubcontract: null,
        sumConsistent: null,
        materialInfo: null,
        materialEquipmentNumber: null,
        materialEquipmentUnit: null,
      },
    ],
    isProfessionSubcontract: null,
    sumConsistent: null,
    materialInfo: null,
    materialEquipmentNumber: null,
    materialEquipmentUnit: null,
  },
  // {
  //   id: 1,
  //   projectId: 100,
  //   parentId: 0,
  //   projectLevelId: 1,
  //   projectNumber: "a00001",
  //   subProjectName: "环球爆破重建项目",
  //   materialEquipment: null,
  //   materialEquipmentConsistent: null,
  //   machineUse: null,
  //   machineUseConsistent: null,
  //   laborPerson: null,
  //   laborPersonConsistent: null,
  //   levelItemType: ProjectType.PROJECT_BASE,
  //   children: [
  //     {
  //       id: "1714894226275405826",
  //       projectId: 100,
  //       parentId: 1,
  //       projectLevelId: "1714894226275405826",
  //       projectNumber: "12222abcdefg",
  //       subProjectName: "导入单项测试234567",
  //       materialEquipment: null,
  //       materialEquipmentConsistent: null,
  //       machineUse: null,
  //       machineUseConsistent: null,
  //       laborPerson: null,
  //       laborPersonConsistent: null,
  //       levelItemType: ProjectType.SINGLE_PROJECT,
  //       children: [
  //         {
  //           id: "1714894226275405827",
  //           projectId: 100,
  //           parentId: "1714894226275405826",
  //           projectLevelId: "1714894226275405827",
  //           projectNumber: "3223123b3344bcdefg",
  //           subProjectName: "导入单位测试234567",
  //           materialEquipment: 0,
  //           materialEquipmentConsistent: 1,
  //           machineUse: 0,
  //           machineUseConsistent: 1,
  //           laborPerson: 0,
  //           laborPersonConsistent: 1,
  //           levelItemType: ProjectType.UNIT_PROJECT,
  //           children: [
  //             {
  //               id: "1714894226275405827",
  //               projectId: 100,
  //               parentId: "1714894226275405826",
  //               projectLevelId: "1714894226275405827",
  //               projectNumber: "0000000",
  //               subProjectName: "特殊的分部",
  //               isEmpty: true,
  //               materialEquipment: 0,
  //               materialEquipmentConsistent: 1,
  //               machineUse: 0,
  //               machineUseConsistent: 1,
  //               laborPerson: 0,
  //               laborPersonConsistent: 1,
  //               levelItemType: ProjectType.DIVISION_PROJECT,
  //               isProfessionSubcontract: 0,
  //               sumConsistent: null,
  //               materialInfo: null,
  //               materialEquipmentNumber: null,
  //               materialEquipmentUnit: null,
  //               children: [
  //                 {
  //                   id: "1714902296099549185",
  //                   projectId: 100,
  //                   parentId: 0,
  //                   projectLevelId: "1714894226275405827",
  //                   projectNumber: "03223232323",
  //                   subProjectName: "分项",
  //                   materialEquipment: 0,
  //                   materialEquipmentConsistent: null,
  //                   machineUse: 0,
  //                   machineUseConsistent: null,
  //                   laborPerson: 0,
  //                   laborPersonConsistent: null,
  //                   levelItemType: ProjectType.ITEM_CHECKLIST,
  //                   children: [],
  //                   isProfessionSubcontract: null,
  //                   sumConsistent: null,
  //                   materialInfo: null,
  //                   materialEquipmentNumber: null,
  //                   materialEquipmentUnit: null,
  //                 },
  //               ],
  //             },
  //           ],
  //           isProfessionSubcontract: 0,
  //           sumConsistent: null,
  //           materialInfo: null,
  //           materialEquipmentNumber: null,
  //           materialEquipmentUnit: null,
  //         },
  //       ],
  //       isProfessionSubcontract: null,
  //       sumConsistent: null,
  //       materialInfo: null,
  //       materialEquipmentNumber: null,
  //       materialEquipmentUnit: null,
  //     },
  //     {
  //       id: "1714829600137293826",
  //       projectId: 100,
  //       parentId: 1,
  //       projectLevelId: "1714829600137293826",
  //       projectNumber: "12222abcdef",
  //       subProjectName: "导入单项测试234567",
  //       materialEquipment: null,
  //       materialEquipmentConsistent: null,
  //       machineUse: null,
  //       machineUseConsistent: null,
  //       laborPerson: null,
  //       laborPersonConsistent: null,
  //       levelItemType: ProjectType.SINGLE_PROJECT,
  //       children: [
  //         {
  //           id: "1714850304812347393",
  //           projectId: 100,
  //           parentId: "1714829600137293826",
  //           projectLevelId: "1714850304812347393",
  //           projectNumber: "123dedd",
  //           subProjectName: "测试单位",
  //           materialEquipment: 0,
  //           materialEquipmentConsistent: 0,
  //           machineUse: 0,
  //           machineUseConsistent: 1,
  //           laborPerson: 0,
  //           laborPersonConsistent: 1,
  //           levelItemType: ProjectType.UNIT_PROJECT,
  //           children: [
  //             {
  //               id: "1714850750498324481",
  //               projectId: 100,
  //               parentId: "1714850304812347393",
  //               projectLevelId: "1714850750498324481",
  //               projectNumber: "df222",
  //               subProjectName: "测试分部2",
  //               materialEquipment: 1,
  //               materialEquipmentConsistent: null,
  //               machineUse: 0,
  //               machineUseConsistent: null,
  //               laborPerson: 0,
  //               laborPersonConsistent: null,
  //               levelItemType: ProjectType.DIVISION_PROJECT,
  //               children: [
  //                 {
  //                   id: "1714882248802734081",
  //                   projectId: 100,
  //                   parentId: 0,
  //                   projectLevelId: "1714850750498324481",
  //                   projectNumber: "010201005027",
  //                   subProjectName: "振冲密实(不填料)",
  //                   materialEquipment: 0,
  //                   materialEquipmentConsistent: null,
  //                   machineUse: 0,
  //                   machineUseConsistent: null,
  //                   laborPerson: 0,
  //                   laborPersonConsistent: null,
  //                   levelItemType: ProjectType.ITEM_CHECKLIST,
  //                   children: [],
  //                   isProfessionSubcontract: null,
  //                   sumConsistent: null,
  //                   materialInfo: null,
  //                   materialEquipmentNumber: null,
  //                   materialEquipmentUnit: null,
  //                 },
  //               ],
  //               isProfessionSubcontract: 0,
  //               sumConsistent: null,
  //               materialInfo: null,
  //               materialEquipmentNumber: null,
  //               materialEquipmentUnit: null,
  //             },
  //           ],
  //           isProfessionSubcontract: 0,
  //           sumConsistent: null,
  //           materialInfo: null,
  //           materialEquipmentNumber: null,
  //           materialEquipmentUnit: null,
  //         },
  //         {
  //           id: "1714829600137293827",
  //           projectId: 100,
  //           parentId: "1714829600137293826",
  //           projectLevelId: "1714829600137293827",
  //           projectNumber: "3223123b3344bcdef",
  //           subProjectName: "导入单位测试23456",
  //           materialEquipment: 0,
  //           materialEquipmentConsistent: 1,
  //           machineUse: 0,
  //           machineUseConsistent: 1,
  //           laborPerson: 1,
  //           laborPersonConsistent: 0,
  //           levelItemType: ProjectType.UNIT_PROJECT,
  //           children: [],
  //           isProfessionSubcontract: 0,
  //           sumConsistent: null,
  //           materialInfo: null,
  //           materialEquipmentNumber: null,
  //           materialEquipmentUnit: null,
  //         },
  //       ],
  //       isProfessionSubcontract: null,
  //       sumConsistent: null,
  //       materialInfo: null,
  //       materialEquipmentNumber: null,
  //       materialEquipmentUnit: null,
  //     },
  //     {
  //       id: "1714829154727374850",
  //       projectId: 100,
  //       parentId: 1,
  //       projectLevelId: "1714829154727374850",
  //       projectNumber: "12222abcde",
  //       subProjectName: "导入单项测试2345",
  //       materialEquipment: null,
  //       materialEquipmentConsistent: null,
  //       machineUse: null,
  //       machineUseConsistent: null,
  //       laborPerson: null,
  //       laborPersonConsistent: null,
  //       levelItemType: ProjectType.SINGLE_PROJECT,
  //       children: [
  //         {
  //           id: "1714829154727374851",
  //           projectId: 100,
  //           parentId: "1714829154727374850",
  //           projectLevelId: "1714829154727374851",
  //           projectNumber: "3223123b3344bcde",
  //           subProjectName: "导入单位测试2345",
  //           materialEquipment: 0,
  //           materialEquipmentConsistent: 1,
  //           machineUse: 0,
  //           machineUseConsistent: 1,
  //           laborPerson: 0,
  //           laborPersonConsistent: 1,
  //           levelItemType: ProjectType.UNIT_PROJECT,
  //           children: [],
  //           isProfessionSubcontract: 0,
  //           sumConsistent: null,
  //           materialInfo: null,
  //           materialEquipmentNumber: null,
  //           materialEquipmentUnit: null,
  //         },
  //       ],
  //       isProfessionSubcontract: null,
  //       sumConsistent: null,
  //       materialInfo: null,
  //       materialEquipmentNumber: null,
  //       materialEquipmentUnit: null,
  //     },
  //     {
  //       id: "1714825990326333442",
  //       projectId: 100,
  //       parentId: 1,
  //       projectLevelId: "1714825990326333442",
  //       projectNumber: "12222abcd",
  //       subProjectName: "导入单项测试234",
  //       materialEquipment: null,
  //       materialEquipmentConsistent: null,
  //       machineUse: null,
  //       machineUseConsistent: null,
  //       laborPerson: null,
  //       laborPersonConsistent: null,
  //       levelItemType: ProjectType.SINGLE_PROJECT,
  //       children: [
  //         {
  //           id: "1714825990326333443",
  //           projectId: 100,
  //           parentId: "1714825990326333442",
  //           projectLevelId: "1714825990326333443",
  //           projectNumber: "3223123b3344bcd",
  //           subProjectName: "导入单位测试234",
  //           materialEquipment: 0,
  //           materialEquipmentConsistent: 1,
  //           machineUse: 0,
  //           machineUseConsistent: 1,
  //           laborPerson: 0,
  //           laborPersonConsistent: 1,
  //           levelItemType: ProjectType.UNIT_PROJECT,
  //           children: [],
  //           isProfessionSubcontract: 0,
  //           sumConsistent: null,
  //           materialInfo: null,
  //           materialEquipmentNumber: null,
  //           materialEquipmentUnit: null,
  //         },
  //       ],
  //       isProfessionSubcontract: null,
  //       sumConsistent: null,
  //       materialInfo: null,
  //       materialEquipmentNumber: null,
  //       materialEquipmentUnit: null,
  //     },
  //     {
  //       id: "1714825253278068738",
  //       projectId: 100,
  //       parentId: 1,
  //       projectLevelId: "1714825253278068738",
  //       projectNumber: "12222abc",
  //       subProjectName: "导入单项测试23",
  //       materialEquipment: null,
  //       materialEquipmentConsistent: null,
  //       machineUse: null,
  //       machineUseConsistent: null,
  //       laborPerson: null,
  //       laborPersonConsistent: null,
  //       levelItemType: ProjectType.SINGLE_PROJECT,
  //       children: [
  //         {
  //           id: "1714825253282263041",
  //           projectId: 100,
  //           parentId: "1714825253278068738",
  //           projectLevelId: "1714825253282263041",
  //           projectNumber: "3223123b3344bc",
  //           subProjectName: "导入单位测试23",
  //           materialEquipment: 0,
  //           materialEquipmentConsistent: 1,
  //           machineUse: 0,
  //           machineUseConsistent: 1,
  //           laborPerson: 0,
  //           laborPersonConsistent: 1,
  //           levelItemType: ProjectType.UNIT_PROJECT,
  //           children: [],
  //           isProfessionSubcontract: 0,
  //           sumConsistent: null,
  //           materialInfo: null,
  //           materialEquipmentNumber: null,
  //           materialEquipmentUnit: null,
  //         },
  //       ],
  //       isProfessionSubcontract: null,
  //       sumConsistent: null,
  //       materialInfo: null,
  //       materialEquipmentNumber: null,
  //       materialEquipmentUnit: null,
  //     },
  //     {
  //       id: "1714570530822983681",
  //       projectId: 100,
  //       parentId: 1,
  //       projectLevelId: "1714570530822983681",
  //       projectNumber: "a12222344",
  //       subProjectName: "导入单项测试1",
  //       materialEquipment: null,
  //       materialEquipmentConsistent: null,
  //       machineUse: null,
  //       machineUseConsistent: null,
  //       laborPerson: null,
  //       laborPersonConsistent: null,
  //       levelItemType: ProjectType.SINGLE_PROJECT,
  //       children: [
  //         {
  //           id: "1714570530822983682",
  //           projectId: 100,
  //           parentId: "1714570530822983681",
  //           projectLevelId: "1714570530822983682",
  //           projectNumber: "b3223123",
  //           subProjectName: "导入单位测试",
  //           materialEquipment: 0,
  //           materialEquipmentConsistent: 1,
  //           machineUse: 0,
  //           machineUseConsistent: 1,
  //           laborPerson: 0,
  //           laborPersonConsistent: 1,
  //           levelItemType: ProjectType.UNIT_PROJECT,
  //           children: [],
  //           isProfessionSubcontract: 0,
  //           sumConsistent: null,
  //           materialInfo: null,
  //           materialEquipmentNumber: null,
  //           materialEquipmentUnit: null,
  //         },
  //       ],
  //       isProfessionSubcontract: null,
  //       sumConsistent: null,
  //       materialInfo: null,
  //       materialEquipmentNumber: null,
  //       materialEquipmentUnit: null,
  //     },
  //     {
  //       id: "1714820042300731393",
  //       projectId: 100,
  //       parentId: 1,
  //       projectLevelId: "1714820042300731393",
  //       projectNumber: "12222ab",
  //       subProjectName: "导入单项测试2",
  //       materialEquipment: null,
  //       materialEquipmentConsistent: null,
  //       machineUse: null,
  //       machineUseConsistent: null,
  //       laborPerson: null,
  //       laborPersonConsistent: null,
  //       levelItemType: ProjectType.SINGLE_PROJECT,
  //       children: [
  //         {
  //           id: "1714820042300731394",
  //           projectId: 100,
  //           parentId: "1714820042300731393",
  //           projectLevelId: "1714820042300731394",
  //           projectNumber: "3223123b3344b",
  //           subProjectName: "导入单位测试2",
  //           materialEquipment: 0,
  //           materialEquipmentConsistent: 1,
  //           machineUse: 0,
  //           machineUseConsistent: 1,
  //           laborPerson: 0,
  //           laborPersonConsistent: 1,
  //           levelItemType: ProjectType.UNIT_PROJECT,
  //           children: [],
  //           isProfessionSubcontract: 0,
  //           sumConsistent: null,
  //           materialInfo: null,
  //           materialEquipmentNumber: null,
  //           materialEquipmentUnit: null,
  //         },
  //       ],
  //       isProfessionSubcontract: null,
  //       sumConsistent: null,
  //       materialInfo: null,
  //       materialEquipmentNumber: null,
  //       materialEquipmentUnit: null,
  //     },
  //     {
  //       id: "1714572057692246018",
  //       projectId: 100,
  //       parentId: 1,
  //       projectLevelId: "1714572057692246018",
  //       projectNumber: "a12222334",
  //       subProjectName: "导入单项测试",
  //       materialEquipment: null,
  //       materialEquipmentConsistent: null,
  //       machineUse: null,
  //       machineUseConsistent: null,
  //       laborPerson: null,
  //       laborPersonConsistent: null,
  //       levelItemType: ProjectType.SINGLE_PROJECT,
  //       children: [
  //         {
  //           id: "1714572057692246019",
  //           projectId: 100,
  //           parentId: "1714572057692246018",
  //           projectLevelId: "1714572057692246019",
  //           projectNumber: "b3223123-A",
  //           subProjectName: "导入单位测试1",
  //           materialEquipment: 0,
  //           materialEquipmentConsistent: 1,
  //           machineUse: 0,
  //           machineUseConsistent: 1,
  //           laborPerson: 0,
  //           laborPersonConsistent: 1,
  //           levelItemType: ProjectType.UNIT_PROJECT,
  //           children: [],
  //           isProfessionSubcontract: 0,
  //           sumConsistent: null,
  //           materialInfo: null,
  //           materialEquipmentNumber: null,
  //           materialEquipmentUnit: null,
  //         },
  //       ],
  //       isProfessionSubcontract: null,
  //       sumConsistent: null,
  //       materialInfo: null,
  //       materialEquipmentNumber: null,
  //       materialEquipmentUnit: null,
  //     },
  //     {
  //       id: "1714572057692246021",
  //       projectId: 100,
  //       parentId: 1,
  //       projectLevelId: "1714572057692246021",
  //       projectNumber: "a12223335",
  //       subProjectName: "导入单项测试2",
  //       materialEquipment: null,
  //       materialEquipmentConsistent: null,
  //       machineUse: null,
  //       machineUseConsistent: null,
  //       laborPerson: null,
  //       laborPersonConsistent: null,
  //       levelItemType: ProjectType.SINGLE_PROJECT,
  //       children: [
  //         {
  //           id: "1714572057692246022",
  //           projectId: 100,
  //           parentId: "1714572057692246021",
  //           projectLevelId: "1714572057692246022",
  //           projectNumber: "b3223123-B",
  //           subProjectName: "导入单位测试2",
  //           materialEquipment: 0,
  //           materialEquipmentConsistent: 1,
  //           machineUse: 0,
  //           machineUseConsistent: 1,
  //           laborPerson: 0,
  //           laborPersonConsistent: 1,
  //           levelItemType: ProjectType.UNIT_PROJECT,
  //           children: [],
  //           isProfessionSubcontract: 0,
  //           sumConsistent: null,
  //           materialInfo: null,
  //           materialEquipmentNumber: null,
  //           materialEquipmentUnit: null,
  //         },
  //       ],
  //       isProfessionSubcontract: null,
  //       sumConsistent: null,
  //       materialInfo: null,
  //       materialEquipmentNumber: null,
  //       materialEquipmentUnit: null,
  //     },
  //     {
  //       id: "1714570748830322690",
  //       projectId: 100,
  //       parentId: 1,
  //       projectLevelId: "1714570748830322690",
  //       projectNumber: "12222a",
  //       subProjectName: "导入单项测试",
  //       materialEquipment: null,
  //       materialEquipmentConsistent: null,
  //       machineUse: null,
  //       machineUseConsistent: null,
  //       laborPerson: null,
  //       laborPersonConsistent: null,
  //       levelItemType: ProjectType.SINGLE_PROJECT,
  //       children: [
  //         {
  //           id: "1714570748830322691",
  //           projectId: 100,
  //           parentId: "1714570748830322690",
  //           projectLevelId: "1714570748830322691",
  //           projectNumber: "3223123b3344",
  //           subProjectName: "导入单位测试",
  //           materialEquipment: 0,
  //           materialEquipmentConsistent: 1,
  //           machineUse: 0,
  //           machineUseConsistent: 1,
  //           laborPerson: 0,
  //           laborPersonConsistent: 1,
  //           levelItemType: ProjectType.UNIT_PROJECT,
  //           children: [],
  //           isProfessionSubcontract: 0,
  //           sumConsistent: null,
  //           materialInfo: null,
  //           materialEquipmentNumber: null,
  //           materialEquipmentUnit: null,
  //         },
  //       ],
  //       isProfessionSubcontract: null,
  //       sumConsistent: null,
  //       materialInfo: null,
  //       materialEquipmentNumber: null,
  //       materialEquipmentUnit: null,
  //     },
  //     {
  //       id: 2,
  //       projectId: 100,
  //       parentId: 1,
  //       projectLevelId: 2,
  //       projectNumber: "00001334411",
  //       subProjectName: "一号楼建设234",
  //       materialEquipment: null,
  //       materialEquipmentConsistent: null,
  //       machineUse: null,
  //       machineUseConsistent: null,
  //       laborPerson: null,
  //       laborPersonConsistent: null,
  //       levelItemType: ProjectType.SINGLE_PROJECT,
  //       children: [
  //         {
  //           id: 6,
  //           projectId: 100,
  //           parentId: 2,
  //           projectLevelId: 6,
  //           projectNumber: "00001001",
  //           subProjectName: "地下室2",
  //           materialEquipment: 0,
  //           materialEquipmentConsistent: 0,
  //           machineUse: 0,
  //           machineUseConsistent: 0,
  //           laborPerson: 0,
  //           laborPersonConsistent: 0,
  //           levelItemType: ProjectType.UNIT_PROJECT,
  //           children: [
  //             {
  //               id: "1712752474596802562",
  //               projectId: 100,
  //               parentId: 6,
  //               projectLevelId: "1712752474596802562",
  //               projectNumber: "123122",
  //               subProjectName: "抬头",
  //               materialEquipment: 1,
  //               materialEquipmentConsistent: null,
  //               machineUse: 1,
  //               machineUseConsistent: null,
  //               laborPerson: 1,
  //               laborPersonConsistent: null,
  //               levelItemType: ProjectType.DIVISION_PROJECT,
  //               children: [],
  //               isProfessionSubcontract: 0,
  //               sumConsistent: null,
  //               materialInfo: null,
  //               materialEquipmentNumber: null,
  //               materialEquipmentUnit: null,
  //             },
  //             {
  //               id: 7,
  //               projectId: 100,
  //               parentId: 6,
  //               projectLevelId: 7,
  //               projectNumber: "00001001001",
  //               subProjectName: "土方123",
  //               materialEquipment: 1,
  //               materialEquipmentConsistent: null,
  //               machineUse: 1,
  //               machineUseConsistent: null,
  //               laborPerson: 1,
  //               laborPersonConsistent: null,
  //               levelItemType: ProjectType.DIVISION_PROJECT,
  //               children: [
  //                 {
  //                   id: "1711996861198225409",
  //                   projectId: 100,
  //                   parentId: 0,
  //                   projectLevelId: 7,
  //                   projectNumber: "0101030002",
  //                   subProjectName: "余方弃置",
  //                   materialEquipment: 0,
  //                   materialEquipmentConsistent: null,
  //                   machineUse: 0,
  //                   machineUseConsistent: null,
  //                   laborPerson: 0,
  //                   laborPersonConsistent: null,
  //                   levelItemType: ProjectType.ITEM_CHECKLIST,
  //                   children: [
  //                     {
  //                       id: "1712089405902913537",
  //                       projectId: 100,
  //                       parentId: "1711996861198225409",
  //                       projectLevelId: 7,
  //                       projectNumber: "010103000305",
  //                       subProjectName: "石方51",
  //                       materialEquipment: 0,
  //                       materialEquipmentConsistent: null,
  //                       machineUse: 0,
  //                       machineUseConsistent: null,
  //                       laborPerson: 0,
  //                       laborPersonConsistent: null,
  //                       levelItemType: ProjectType.ITEM_PROCESS,
  //                       children: [],
  //                       isProfessionSubcontract: null,
  //                       sumConsistent: null,
  //                       materialInfo: null,
  //                       materialEquipmentNumber: null,
  //                       materialEquipmentUnit: null,
  //                     },
  //                     {
  //                       id: "1712080903868375041",
  //                       projectId: 100,
  //                       parentId: "1711996861198225409",
  //                       projectLevelId: 7,
  //                       projectNumber: "010103000103",
  //                       subProjectName: "余方弃置工序3",
  //                       materialEquipment: 0,
  //                       materialEquipmentConsistent: null,
  //                       machineUse: 0,
  //                       machineUseConsistent: null,
  //                       laborPerson: 0,
  //                       laborPersonConsistent: null,
  //                       levelItemType: ProjectType.ITEM_PROCESS,
  //                       children: [],
  //                       isProfessionSubcontract: null,
  //                       sumConsistent: null,
  //                       materialInfo: null,
  //                       materialEquipmentNumber: null,
  //                       materialEquipmentUnit: null,
  //                     },
  //                     {
  //                       id: "1712011973858426882",
  //                       projectId: 100,
  //                       parentId: "1711996861198225409",
  //                       projectLevelId: 7,
  //                       projectNumber: "010103000102",
  //                       subProjectName: "余方弃置工序2",
  //                       materialEquipment: 0,
  //                       materialEquipmentConsistent: null,
  //                       machineUse: 0,
  //                       machineUseConsistent: null,
  //                       laborPerson: 0,
  //                       laborPersonConsistent: null,
  //                       levelItemType: ProjectType.ITEM_PROCESS,
  //                       children: [],
  //                       isProfessionSubcontract: null,
  //                       sumConsistent: null,
  //                       materialInfo: null,
  //                       materialEquipmentNumber: null,
  //                       materialEquipmentUnit: null,
  //                     },
  //                   ],
  //                   isProfessionSubcontract: null,
  //                   sumConsistent: null,
  //                   materialInfo: null,
  //                   materialEquipmentNumber: null,
  //                   materialEquipmentUnit: null,
  //                 },
  //                 {
  //                   id: "1711996512055971841",
  //                   projectId: 100,
  //                   parentId: 0,
  //                   projectLevelId: 7,
  //                   projectNumber: "0101030001",
  //                   subProjectName: "回填方",
  //                   materialEquipment: 0,
  //                   materialEquipmentConsistent: null,
  //                   machineUse: 0,
  //                   machineUseConsistent: null,
  //                   laborPerson: 0,
  //                   laborPersonConsistent: null,
  //                   levelItemType: ProjectType.ITEM_CHECKLIST,
  //                   children: [],
  //                   isProfessionSubcontract: null,
  //                   sumConsistent: null,
  //                   materialInfo: null,
  //                   materialEquipmentNumber: null,
  //                   materialEquipmentUnit: null,
  //                 },
  //               ],
  //               isProfessionSubcontract: 1,
  //               sumConsistent: null,
  //               materialInfo: null,
  //               materialEquipmentNumber: null,
  //               materialEquipmentUnit: null,
  //             },
  //           ],
  //           isProfessionSubcontract: 0,
  //           sumConsistent: null,
  //           materialInfo: null,
  //           materialEquipmentNumber: null,
  //           materialEquipmentUnit: null,
  //         },
  //         {
  //           id: "1713813377211592705",
  //           projectId: 100,
  //           parentId: 2,
  //           projectLevelId: "1713813377211592705",
  //           projectNumber: "ssssss",
  //           subProjectName: "测试名称",
  //           materialEquipment: 0,
  //           materialEquipmentConsistent: 1,
  //           machineUse: 0,
  //           machineUseConsistent: 1,
  //           laborPerson: 0,
  //           laborPersonConsistent: 1,
  //           levelItemType: ProjectType.UNIT_PROJECT,
  //           children: [],
  //           isProfessionSubcontract: 0,
  //           sumConsistent: null,
  //           materialInfo: null,
  //           materialEquipmentNumber: null,
  //           materialEquipmentUnit: null,
  //         },
  //         {
  //           id: "1712752595875102721",
  //           projectId: 100,
  //           parentId: 2,
  //           projectLevelId: "1712752595875102721",
  //           projectNumber: "321312",
  //           subProjectName: "防水",
  //           materialEquipment: 0,
  //           materialEquipmentConsistent: 1,
  //           machineUse: 0,
  //           machineUseConsistent: 1,
  //           laborPerson: 0,
  //           laborPersonConsistent: 1,
  //           levelItemType: ProjectType.UNIT_PROJECT,
  //           children: [],
  //           isProfessionSubcontract: 0,
  //           sumConsistent: null,
  //           materialInfo: null,
  //           materialEquipmentNumber: null,
  //           materialEquipmentUnit: null,
  //         },
  //       ],
  //       isProfessionSubcontract: null,
  //       sumConsistent: null,
  //       materialInfo: null,
  //       materialEquipmentNumber: null,
  //       materialEquipmentUnit: null,
  //     },
  //     {
  //       id: "1713888085542129665",
  //       projectId: 100,
  //       parentId: 1,
  //       projectLevelId: "1713888085542129665",
  //       projectNumber: "555995",
  //       subProjectName: "删除单项工程",
  //       materialEquipment: null,
  //       materialEquipmentConsistent: null,
  //       machineUse: null,
  //       machineUseConsistent: null,
  //       laborPerson: null,
  //       laborPersonConsistent: null,
  //       levelItemType: ProjectType.SINGLE_PROJECT,
  //       children: [],
  //       isProfessionSubcontract: null,
  //       sumConsistent: null,
  //       materialInfo: null,
  //       materialEquipmentNumber: null,
  //       materialEquipmentUnit: null,
  //     },
  //     {
  //       id: "1713855773735604226",
  //       projectId: 100,
  //       parentId: 1,
  //       projectLevelId: "1713855773735604226",
  //       projectNumber: "45656456",
  //       subProjectName: "单项工程41",
  //       materialEquipment: null,
  //       materialEquipmentConsistent: null,
  //       machineUse: null,
  //       machineUseConsistent: null,
  //       laborPerson: null,
  //       laborPersonConsistent: null,
  //       levelItemType: ProjectType.SINGLE_PROJECT,
  //       children: [
  //         {
  //           id: "1713855858536042497",
  //           projectId: 100,
  //           parentId: "1713855773735604226",
  //           projectLevelId: "1713855858536042497",
  //           projectNumber: "32432",
  //           subProjectName: "额发给我",
  //           materialEquipment: 0,
  //           materialEquipmentConsistent: 1,
  //           machineUse: 0,
  //           machineUseConsistent: 1,
  //           laborPerson: 0,
  //           laborPersonConsistent: 1,
  //           levelItemType: ProjectType.UNIT_PROJECT,
  //           children: [],
  //           isProfessionSubcontract: 0,
  //           sumConsistent: null,
  //           materialInfo: null,
  //           materialEquipmentNumber: null,
  //           materialEquipmentUnit: null,
  //         },
  //       ],
  //       isProfessionSubcontract: null,
  //       sumConsistent: null,
  //       materialInfo: null,
  //       materialEquipmentNumber: null,
  //       materialEquipmentUnit: null,
  //     },
  //     {
  //       id: 14,
  //       projectId: 100,
  //       parentId: 1,
  //       projectLevelId: 14,
  //       projectNumber: "电饭锅13",
  //       subProjectName: "而各环节2",
  //       materialEquipment: null,
  //       materialEquipmentConsistent: null,
  //       machineUse: null,
  //       machineUseConsistent: null,
  //       laborPerson: null,
  //       laborPersonConsistent: null,
  //       levelItemType: ProjectType.SINGLE_PROJECT,
  //       children: [
  //         {
  //           id: "1713850466288488449",
  //           projectId: 100,
  //           parentId: 14,
  //           projectLevelId: "1713850466288488449",
  //           projectNumber: "1211233131",
  //           subProjectName: "33大大-同级",
  //           materialEquipment: 1,
  //           materialEquipmentConsistent: 0,
  //           machineUse: 0,
  //           machineUseConsistent: 1,
  //           laborPerson: 0,
  //           laborPersonConsistent: 1,
  //           levelItemType: ProjectType.UNIT_PROJECT,
  //           children: [],
  //           isProfessionSubcontract: 0,
  //           sumConsistent: null,
  //           materialInfo: null,
  //           materialEquipmentNumber: null,
  //           materialEquipmentUnit: null,
  //         },
  //         {
  //           id: "1713850291595726849",
  //           projectId: 100,
  //           parentId: 14,
  //           projectLevelId: "1713850291595726849",
  //           projectNumber: "sfwfwefef",
  //           subProjectName: "而各环节2-child",
  //           materialEquipment: 0,
  //           materialEquipmentConsistent: 1,
  //           machineUse: 0,
  //           machineUseConsistent: 1,
  //           laborPerson: 0,
  //           laborPersonConsistent: 1,
  //           levelItemType: ProjectType.UNIT_PROJECT,
  //           children: [],
  //           isProfessionSubcontract: 0,
  //           sumConsistent: null,
  //           materialInfo: null,
  //           materialEquipmentNumber: null,
  //           materialEquipmentUnit: null,
  //         },
  //         {
  //           id: 29,
  //           projectId: 100,
  //           parentId: 14,
  //           projectLevelId: 29,
  //           projectNumber: "3",
  //           subProjectName: "33大大",
  //           materialEquipment: 0,
  //           materialEquipmentConsistent: 0,
  //           machineUse: 0,
  //           machineUseConsistent: 0,
  //           laborPerson: 0,
  //           laborPersonConsistent: 0,
  //           levelItemType: ProjectType.UNIT_PROJECT,
  //           children: [
  //             {
  //               id: "1713850393047552001",
  //               projectId: 100,
  //               parentId: 29,
  //               projectLevelId: "1713850393047552001",
  //               projectNumber: "sssssssssswdw",
  //               subProjectName: "33大大-分部",
  //               materialEquipment: 1,
  //               materialEquipmentConsistent: null,
  //               machineUse: 1,
  //               machineUseConsistent: null,
  //               laborPerson: 1,
  //               laborPersonConsistent: null,
  //               levelItemType: ProjectType.DIVISION_PROJECT,
  //               children: [],
  //               isProfessionSubcontract: 0,
  //               sumConsistent: null,
  //               materialInfo: null,
  //               materialEquipmentNumber: null,
  //               materialEquipmentUnit: null,
  //             },
  //           ],
  //           isProfessionSubcontract: 0,
  //           sumConsistent: null,
  //           materialInfo: null,
  //           materialEquipmentNumber: null,
  //           materialEquipmentUnit: null,
  //         },
  //       ],
  //       isProfessionSubcontract: null,
  //       sumConsistent: null,
  //       materialInfo: null,
  //       materialEquipmentNumber: null,
  //       materialEquipmentUnit: null,
  //     },
  //     {
  //       id: 15,
  //       projectId: 100,
  //       parentId: 1,
  //       projectLevelId: 15,
  //       projectNumber: "水电费4",
  //       subProjectName: "斤斤计较3334",
  //       materialEquipment: null,
  //       materialEquipmentConsistent: null,
  //       machineUse: null,
  //       machineUseConsistent: null,
  //       laborPerson: null,
  //       laborPersonConsistent: null,
  //       levelItemType: ProjectType.SINGLE_PROJECT,
  //       children: [
  //         {
  //           id: "1714219607990190081",
  //           projectId: 100,
  //           parentId: 15,
  //           projectLevelId: "1714219607990190081",
  //           projectNumber: "是的撒的",
  //           subProjectName: "我对我群",
  //           materialEquipment: 0,
  //           materialEquipmentConsistent: 1,
  //           machineUse: 0,
  //           machineUseConsistent: 1,
  //           laborPerson: 0,
  //           laborPersonConsistent: 1,
  //           levelItemType: ProjectType.UNIT_PROJECT,
  //           children: [],
  //           isProfessionSubcontract: 0,
  //           sumConsistent: null,
  //           materialInfo: null,
  //           materialEquipmentNumber: null,
  //           materialEquipmentUnit: null,
  //         },
  //         {
  //           id: 28,
  //           projectId: 100,
  //           parentId: 15,
  //           projectLevelId: 28,
  //           projectNumber: "1",
  //           subProjectName: "222",
  //           materialEquipment: 0,
  //           materialEquipmentConsistent: 1,
  //           machineUse: 0,
  //           machineUseConsistent: 1,
  //           laborPerson: 0,
  //           laborPersonConsistent: 1,
  //           levelItemType: ProjectType.UNIT_PROJECT,
  //           children: [],
  //           isProfessionSubcontract: 0,
  //           sumConsistent: null,
  //           materialInfo: null,
  //           materialEquipmentNumber: null,
  //           materialEquipmentUnit: null,
  //         },
  //       ],
  //       isProfessionSubcontract: null,
  //       sumConsistent: null,
  //       materialInfo: null,
  //       materialEquipmentNumber: null,
  //       materialEquipmentUnit: null,
  //     },
  //     {
  //       id: 16,
  //       projectId: 100,
  //       parentId: 1,
  //       projectLevelId: 16,
  //       projectNumber: "对对对",
  //       subProjectName: "113333",
  //       materialEquipment: null,
  //       materialEquipmentConsistent: null,
  //       machineUse: null,
  //       machineUseConsistent: null,
  //       laborPerson: null,
  //       laborPersonConsistent: null,
  //       levelItemType: ProjectType.SINGLE_PROJECT,
  //       children: [
  //         {
  //           id: 27,
  //           projectId: 100,
  //           parentId: 16,
  //           projectLevelId: 27,
  //           projectNumber: "233",
  //           subProjectName: "对对对",
  //           materialEquipment: 0,
  //           materialEquipmentConsistent: 1,
  //           machineUse: 0,
  //           machineUseConsistent: 1,
  //           laborPerson: 0,
  //           laborPersonConsistent: 1,
  //           levelItemType: ProjectType.UNIT_PROJECT,
  //           children: [],
  //           isProfessionSubcontract: 0,
  //           sumConsistent: null,
  //           materialInfo: null,
  //           materialEquipmentNumber: null,
  //           materialEquipmentUnit: null,
  //         },
  //       ],
  //       isProfessionSubcontract: null,
  //       sumConsistent: null,
  //       materialInfo: null,
  //       materialEquipmentNumber: null,
  //       materialEquipmentUnit: null,
  //     },
  //     {
  //       id: 17,
  //       projectId: 100,
  //       parentId: 1,
  //       projectLevelId: 17,
  //       projectNumber: "123123",
  //       subProjectName: "单项工程",
  //       materialEquipment: null,
  //       materialEquipmentConsistent: null,
  //       machineUse: null,
  //       machineUseConsistent: null,
  //       laborPerson: null,
  //       laborPersonConsistent: null,
  //       levelItemType: ProjectType.SINGLE_PROJECT,
  //       children: [
  //         {
  //           id: 36,
  //           projectId: 100,
  //           parentId: 17,
  //           projectLevelId: 36,
  //           projectNumber: "2312312",
  //           subProjectName: "单位工程41",
  //           materialEquipment: 0,
  //           materialEquipmentConsistent: 1,
  //           machineUse: 0,
  //           machineUseConsistent: 1,
  //           laborPerson: 0,
  //           laborPersonConsistent: 1,
  //           levelItemType: ProjectType.UNIT_PROJECT,
  //           children: [
  //             {
  //               id: "1713757758098206721",
  //               projectId: 100,
  //               parentId: 36,
  //               projectLevelId: "1713757758098206721",
  //               projectNumber: "002133323",
  //               subProjectName: "韩树飞-测试1",
  //               materialEquipment: 0,
  //               materialEquipmentConsistent: null,
  //               machineUse: 0,
  //               machineUseConsistent: null,
  //               laborPerson: 0,
  //               laborPersonConsistent: null,
  //               levelItemType: ProjectType.DIVISION_PROJECT,
  //               children: [],
  //               isProfessionSubcontract: 0,
  //               sumConsistent: null,
  //               materialInfo: null,
  //               materialEquipmentNumber: null,
  //               materialEquipmentUnit: null,
  //             },
  //             {
  //               id: 37,
  //               projectId: 100,
  //               parentId: 36,
  //               projectLevelId: 37,
  //               projectNumber: "3124",
  //               subProjectName: "分部工程33",
  //               materialEquipment: 0,
  //               materialEquipmentConsistent: null,
  //               machineUse: 0,
  //               machineUseConsistent: null,
  //               laborPerson: 0,
  //               laborPersonConsistent: null,
  //               levelItemType: ProjectType.DIVISION_PROJECT,
  //               children: [],
  //               isProfessionSubcontract: 0,
  //               sumConsistent: null,
  //               materialInfo: null,
  //               materialEquipmentNumber: null,
  //               materialEquipmentUnit: null,
  //             },
  //           ],
  //           isProfessionSubcontract: 0,
  //           sumConsistent: null,
  //           materialInfo: null,
  //           materialEquipmentNumber: null,
  //           materialEquipmentUnit: null,
  //         },
  //         {
  //           id: 20,
  //           projectId: 100,
  //           parentId: 17,
  //           projectLevelId: 20,
  //           projectNumber: "1111",
  //           subProjectName: "单位工程3",
  //           materialEquipment: 0,
  //           materialEquipmentConsistent: 1,
  //           machineUse: 0,
  //           machineUseConsistent: 1,
  //           laborPerson: 0,
  //           laborPersonConsistent: 1,
  //           levelItemType: ProjectType.UNIT_PROJECT,
  //           children: [],
  //           isProfessionSubcontract: 0,
  //           sumConsistent: null,
  //           materialInfo: null,
  //           materialEquipmentNumber: null,
  //           materialEquipmentUnit: null,
  //         },
  //         {
  //           id: 18,
  //           projectId: 100,
  //           parentId: 17,
  //           projectLevelId: 18,
  //           projectNumber: "123",
  //           subProjectName: "单位工程",
  //           materialEquipment: 0,
  //           materialEquipmentConsistent: 1,
  //           machineUse: 0,
  //           machineUseConsistent: 1,
  //           laborPerson: 0,
  //           laborPersonConsistent: 1,
  //           levelItemType: ProjectType.UNIT_PROJECT,
  //           children: [],
  //           isProfessionSubcontract: 0,
  //           sumConsistent: null,
  //           materialInfo: null,
  //           materialEquipmentNumber: null,
  //           materialEquipmentUnit: null,
  //         },
  //       ],
  //       isProfessionSubcontract: null,
  //       sumConsistent: null,
  //       materialInfo: null,
  //       materialEquipmentNumber: null,
  //       materialEquipmentUnit: null,
  //     },
  //     {
  //       id: 19,
  //       projectId: 100,
  //       parentId: 1,
  //       projectLevelId: 19,
  //       projectNumber: "1111",
  //       subProjectName: "单项工程2",
  //       materialEquipment: null,
  //       materialEquipmentConsistent: null,
  //       machineUse: null,
  //       machineUseConsistent: null,
  //       laborPerson: null,
  //       laborPersonConsistent: null,
  //       levelItemType: ProjectType.SINGLE_PROJECT,
  //       children: [
  //         {
  //           id: 21,
  //           projectId: 100,
  //           parentId: 19,
  //           projectLevelId: 21,
  //           projectNumber: "222",
  //           subProjectName: "单位工程3",
  //           materialEquipment: 0,
  //           materialEquipmentConsistent: 1,
  //           machineUse: 0,
  //           machineUseConsistent: 1,
  //           laborPerson: 0,
  //           laborPersonConsistent: 1,
  //           levelItemType: ProjectType.UNIT_PROJECT,
  //           children: [],
  //           isProfessionSubcontract: 0,
  //           sumConsistent: null,
  //           materialInfo: null,
  //           materialEquipmentNumber: null,
  //           materialEquipmentUnit: null,
  //         },
  //       ],
  //       isProfessionSubcontract: null,
  //       sumConsistent: null,
  //       materialInfo: null,
  //       materialEquipmentNumber: null,
  //       materialEquipmentUnit: null,
  //     },
  //     {
  //       id: 22,
  //       projectId: 100,
  //       parentId: 1,
  //       projectLevelId: 22,
  //       projectNumber: "333",
  //       subProjectName: "单项工程3",
  //       materialEquipment: null,
  //       materialEquipmentConsistent: null,
  //       machineUse: null,
  //       machineUseConsistent: null,
  //       laborPerson: null,
  //       laborPersonConsistent: null,
  //       levelItemType: ProjectType.SINGLE_PROJECT,
  //       children: [
  //         {
  //           id: 24,
  //           projectId: 100,
  //           parentId: 22,
  //           projectLevelId: 24,
  //           projectNumber: "3334",
  //           subProjectName: "单位工程5",
  //           materialEquipment: 0,
  //           materialEquipmentConsistent: 1,
  //           machineUse: 0,
  //           machineUseConsistent: 1,
  //           laborPerson: 0,
  //           laborPersonConsistent: 1,
  //           levelItemType: ProjectType.UNIT_PROJECT,
  //           children: [
  //             {
  //               id: 25,
  //               projectId: 100,
  //               parentId: 24,
  //               projectLevelId: 25,
  //               projectNumber: "33333",
  //               subProjectName: "分部工程1",
  //               materialEquipment: 0,
  //               materialEquipmentConsistent: null,
  //               machineUse: 0,
  //               machineUseConsistent: null,
  //               laborPerson: 0,
  //               laborPersonConsistent: null,
  //               levelItemType: ProjectType.DIVISION_PROJECT,
  //               children: [],
  //               isProfessionSubcontract: 0,
  //               sumConsistent: null,
  //               materialInfo: null,
  //               materialEquipmentNumber: null,
  //               materialEquipmentUnit: null,
  //             },
  //             {
  //               id: 26,
  //               projectId: 100,
  //               parentId: 24,
  //               projectLevelId: 26,
  //               projectNumber: "3333",
  //               subProjectName: "分部工程3",
  //               materialEquipment: 0,
  //               materialEquipmentConsistent: null,
  //               machineUse: 0,
  //               machineUseConsistent: null,
  //               laborPerson: 0,
  //               laborPersonConsistent: null,
  //               levelItemType: ProjectType.DIVISION_PROJECT,
  //               children: [],
  //               isProfessionSubcontract: 0,
  //               sumConsistent: null,
  //               materialInfo: null,
  //               materialEquipmentNumber: null,
  //               materialEquipmentUnit: null,
  //             },
  //           ],
  //           isProfessionSubcontract: 0,
  //           sumConsistent: null,
  //           materialInfo: null,
  //           materialEquipmentNumber: null,
  //           materialEquipmentUnit: null,
  //         },
  //         {
  //           id: 23,
  //           projectId: 100,
  //           parentId: 22,
  //           projectLevelId: 23,
  //           projectNumber: "333333",
  //           subProjectName: "单位工程4",
  //           materialEquipment: 0,
  //           materialEquipmentConsistent: 1,
  //           machineUse: 0,
  //           machineUseConsistent: 1,
  //           laborPerson: 0,
  //           laborPersonConsistent: 1,
  //           levelItemType: ProjectType.UNIT_PROJECT,
  //           children: [],
  //           isProfessionSubcontract: 0,
  //           sumConsistent: null,
  //           materialInfo: null,
  //           materialEquipmentNumber: null,
  //           materialEquipmentUnit: null,
  //         },
  //       ],
  //       isProfessionSubcontract: null,
  //       sumConsistent: null,
  //       materialInfo: null,
  //       materialEquipmentNumber: null,
  //       materialEquipmentUnit: null,
  //     },
  //   ],
  //   isProfessionSubcontract: null,
  //   sumConsistent: null,
  //   materialInfo: null,
  //   materialEquipmentNumber: null,
  //   materialEquipmentUnit: null,
  // },
];

export function constructTreeData(treeDatas: OrgTree<number | string>[]) {
  const data: OrgTree<number | string>[] = deepClone(treeDatas) || [];

  const parseFn = (data: OrgTree) => {
    if (data.levelItemType === ProjectType.UNIT_PROJECT) {
      // 如果是单位工程  就需要判断是不是分部还是分项
      if (!data.children?.length) {
        return;
      }

      // 记住哪些child是分项
      const itemCheckListIndexs: number[] = [];
      // 存储是分项的item
      const itemCheckListItems: OrgTree[] = [];

      // 如果是单位工程，则判断子项是分部还是分项
      data.children.forEach((child, childIndex) => {
        // 如果子项是分项 就需要添加一个特殊的分部(这里需要注意  这些没有挂在在分部上面的分项都应该)
        if (child.levelItemType === ProjectType.ITEM_CHECKLIST) {
          // data[]
          itemCheckListIndexs.push(childIndex);
          itemCheckListItems.push(child);
        }
      });
      // 找到了不是分部而是分项清单的items后  就应该用一个特殊的盒子装起来
      const emptyDivisionItem: OrgTree = {
        isEmpty: true,
        levelItemType: ProjectType.DIVISION_PROJECT,
        children: itemCheckListItems,
        // children:data.children.filter((_, index) => !itemCheckListIndexs.includes(index))
      };
      data.children = data.children.filter(
        (_, index) => !itemCheckListIndexs.includes(index)
      );

      data.children.push(emptyDivisionItem);
    } else if (data.children?.length) {
      data.children.forEach((child) => parseFn(child));
    }
  };
  data?.forEach((item) => parseFn(item));
  return data;
}
